### ISSUE TITLE
How do I initialize the db tables when running the sample app?

### ISSUE THREAD

**Issue by pabl0rg** [felipecsl/kales#13]
The sample app comes configured to use a postgres db.  

I set one up and edited the database.yml but how do I create the tables in order to avoid this exception:

```
 Position: 15 [statement:"select * from videos", rewritten:"select * from videos", parsed:"ParsedSql{sql='select * from videos', parameters=ParsedParameters{positional=false, parameterNames=[]}}", arguments:{positional:{}, named:{}, finder:[]}]
        at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1568)
        at org.jdbi.v3.core.result.ResultProducers.lambda$getResultSet$2(ResultProducers.java:68)
        at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
        at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:141)
        at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:197)
        at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:186)
        at kales.sample.app.models.Video$Companion.all(Video.kt:21)
        at kales.sample.app.controllers.ExampleController.index(ExampleController.kt:11)
        ... 50 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "videos" does not exist
  Position: 15
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
        at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31)
        at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1560)
        ... 57 common frames omitted
```

**Comment by felipecsl** [comment]
That's not implemented yet! Once we get #12 merged then we'll be able to have database migrations to initialize the db, but for the time being you'll need to create and initialize the database by yourself!

**Comment by pabl0rg** [comment]
ok, that's what i did, but thought there might be another way.

**Comment by felipecsl** [comment]
This is now possible by running `kales db:create` and `kales db:migrate`
